---

- user: name={{ jenkins_user }} shell=/usr/bin/bash generate_ssh_key=yes state=present
  sudo: yes
  when: credentials is defined

- name: "copy credentials configurations to master"
  copy: src={{ credentials }} dest={{ jenkins_home }}/credentials.xml group={{ jenkins_group }} owner={{ jenkins_user }} mode=0644
  when: credentials is defined
  with_dict: "{{ nodes }}"
  notify:
  - restart jenkins