---

- user: name={{ jenkins_user }} shell=/usr/bin/bash generate_ssh_key=yes state=present
  sudo: yes
  when: credentials is defined

- name: "copy credentials configurations to master"
  copy: src={{ credentials }} dest={{ jenkins_home|default('/var/lib/jenkins') }}/credentials.xml group={{ jenkins_group|default('jenkins') }} owner={{ jenkins_user|default('jenkins') }} mode=0644
  when: credentials is defined
  with_dict: "{{ nodes }}"
  notify:
  - "restart jenkins"