---

- shell: echo "{{ jenkins_args }}" | sed -r 's/^.*--prefix=(.*)$/\1/g'
  register: jenkins_ctx
  when: jenkins_args is defined
  changed_when: False

- get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=0644
  
- rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- yum_version: name=jenkins version="{{ jenkins_version }}"
  register: package
  when: jenkins_version is defined
  
- yum: name=libxml2 state=present
  when: jobs is defined or nodes is defined
 
- name: "install rpm : {{ package.label }}"
  yum: name="{{ package.label }}" state=present
  
- name: "configure jenkins"
  template: src=jenkins.j2 dest=/etc/sysconfig/jenkins owner=root group=root mode=0600
  notify: 
  - "restart jenkins"
  
- name: "run jenkins as another user"
  shell: chown -R {{ jenkins_user|default('jenkins') }}:{{ jenkins_group|default('jenkins') }} {{ jenkins_home }} /var/cache/jenkins /var/log/jenkins
  when: jenkins_user != 'jenkins' or jenkins_group != 'jenkins'
  notify: 
  - "restart jenkins"
  
- service: name=jenkins state=started
  
- name: "Create Jenkins CLI destination directory: {{ jenkins_dest }}"
  file: path={{ jenkins_dest }} state=directory

- name: "Get Jenkins CLI"
  get_url: url=http://localhost:{{ jenkins_port|default(8080) }}{{ jenkins_ctx.stdout|default('') }}/jnlpJars/jenkins-cli.jar dest={{ jenkins_cli_dest }} mode=0440
  register: jenkins_local_cli
  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
  retries: 5
  delay: 10
  
- include: plugins.yml

- include: credentials.yml

- include: nodes.yml

- include: jobs.yml
